name: CICD testing
on: push
jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: download repo
              uses: actions/checkout@v4
            - name: welcome page
              run: echo "welcome to the github"

            - name: read the file
              run: cat README.md
            - name: execute cowsay
              run: cowsay -f dragon "this is a dragon symbol" >> dragon.txt
            - name:  list the files
              run: ls
            - name: Read the 2nd file
              run : cat dragon.txt