name: CICD testing
on: push
jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: download repo
              uses: actions/checkout@v4
            - name: install the cowsay
              run: sudo apt-get install cowsay -y
            - name: execute cowsay
              run: cowsay -f dragon "this is a dragon symbol" >> dragon.txt
           
            - name: Welcome and list the files
              run: | 
                cat README.md 
                echo "welcome to the github"
                ls
                cat dragon.txt